service: bandonfews-serverless

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
      
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    FEWS_URL: "http://www.bandonfloodwarning.ie/main.php"
    FUSIONTABLES_ID: "103YIcARoxuaWT7NfZ8mVBzY554sF_3ONYC1N3DE"

functions:
  check:
    handler: check.check
    events:
      - http:
          path: bandonfews
          method: get
          cors: true
  cron:
    handler: check.check
    events:
      # Invoke Lambda function every 15 mins
      - schedule: rate(15 minutes)
